x-resource-limits: &resource_limits
  mem_limit: ${BENCH_MEMORY_LIMIT:-4g}
  cpus: ${BENCH_CPU_LIMIT:-4}

x-tmpfs-options: &tmpfs_defaults
  o: 'rw,size=${BENCH_TMPFS_SIZE:-1073741824}'

services:
  eventdbx:
    image: thachp/eventdbx:latest
    volumes:
      - eventdbx-data:/var/lib/eventdbx
    <<: *resource_limits

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: bench
      POSTGRES_PASSWORD: bench
      POSTGRES_DB: bench
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U bench']
      interval: 5s
      timeout: 3s
      retries: 10
    tmpfs:
      - /var/lib/postgresql/data:rw,size=${BENCH_TMPFS_SIZE:-1073741824}
    <<: *resource_limits

  mongodb:
    image: mongo:7
    command: ['--wiredTigerCacheSizeGB', '${BENCH_MONGO_CACHE_GB:-1.0}']
    environment:
      MONGO_INITDB_ROOT_USERNAME: bench
      MONGO_INITDB_ROOT_PASSWORD: bench
    healthcheck:
      test:
        [
          'CMD',
          'mongosh',
          '--username',
          'bench',
          '--password',
          'bench',
          '--eval',
          'db.runCommand({ping:1})',
        ]
      interval: 5s
      timeout: 3s
      retries: 12
    tmpfs:
      - /data/db:rw,size=${BENCH_TMPFS_SIZE:-1073741824}
    <<: *resource_limits

  bench:
    build:
      context: ..
      dockerfile: benchmarks/Dockerfile
    env_file:
      - bench.toml
    environment:
      EVENTDBX_PG_DSN: 'host=postgres user=bench password=bench dbname=bench'
      EVENTDBX_MONGO_URI: 'mongodb://bench:bench@mongodb:27017/?authSource=admin'
      EVENTDBX_MONGO_DB: 'bench'
      EVENTDBX_MONGO_COLLECTION: 'events'
      EVENTDBX_CONFIG_PATH: '/eventdbx/.eventdbx/config.toml'
      EVENTDBX_SOCKET_ADDR: 'eventdbx:6363'
    depends_on:
      eventdbx:
        condition: service_started
      postgres:
        condition: service_healthy
      mongodb:
        condition: service_healthy
    volumes:
      - ..:/workspace
      - eventdbx-data:/eventdbx
    working_dir: /workspace
    command:
      [
        'cargo',
        '-Z',
        'unstable-options',
        'bench',
        '--bench',
        'backend_comparison',
        '--features',
        'bench-postgres,bench-mongodb',
      ]
    <<: *resource_limits

volumes:
  eventdbx-data:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
      o: 'rw,size=${BENCH_TMPFS_SIZE:-1073741824}'
